#+TITLE: Welcome to my little patch of internet!

This blog is intended to host my personal content where I write about things I
care about - information security, programming, /crêpes au sucre/, Emacs and
other UNIX-based systems. You get the idea... This is not a polished magazine;
it’s a patchwork of rants, experiments and unfinished work, written in plain
language. Oh and, disclaimer, I can sometimes be pretty offensive.


If I occasionally write something for a punctual, one-of topic, it will be
published as a [[./posts/][blog post]]. The [[./notes/][notes]] section points toward more lengthy content
that /might/ get updated over time. Resources that were particularly useful and
interesting to me are kept under [[./links.org][links]]. Information about this website and my
contact details can be found in the [[./about.org][about]] page. What is currently on my mind is
on my [[./now.org][now]] page.

With this out of the way, I wish you happy reading!

* Latest posts

#+INCLUDE: "./posts/index-no-preview.org" :lines "3-7"

A list of all blog posts is available [[file:./posts/index.org][here]]. The elderly are welcome to use the
[[./rss.xml][RSS feed]].
