#+TITLE: Hello World from Org
#+DATE: [2025-05-25 Sun]
#+INCLUDE: ../../templates/post.org


#+begin_preview
I describe /yet-another-simple-publishing-setup/ for a static website using
Emacs's [[https://orgmode.org/][Org mode]]. While there are plenty of resources on the topic available
already, I wanted to document my setup here for self-reference. Maybe someone
will take away an idea or two.
#+end_preview

#+begin_src sh
skywhi@dreamland:~/blog$ echo "Hello World Wild Web!" > posts/hello.org
skywhi@dreamland:~/blog$ make update && make publish
skywhi@dreamland:~/blog$ # make blogging great again!
#+end_src

{{{toc(Contents:,6)}}}

* Rationale
:PROPERTIES:
:CUSTOM_ID: rationale
:END:

I figured the time had come to host some of my modest content online for
sharing, fun, persistence, easy access and all the other usual suspects. Going
into this adventure there were only a few requirements that I wanted my website
to meet:

- Content should be written in my favorite [[https://www.gnu.org/software/emacs/][text editor]] with [[https://orgmode.org/][Org mode]].
- No need for any back-end or front-end logic: serving a static website without
  any fancy HTML/CSS/JS shenanigans will be more than fine.
- The website should be standalone so that it can be viewed offline as well.
- Convenient hosting: hustling with administrating a web-server for such a small
  project would not make any sense to me.

Let me explain. I have been using Emacs and Org mode for several years now. Its
markup language really fits my needs and I have integrated my Org files with the
agenda and other nifty features Emacs and Org have to offer. The ability to hack
their behavior in elisp is also a great plus to me as it immensely increases the
flexibility of this setup.

When it comes to this website, I want to be able to turn whatever I am currently
working on into publishable content without having to spend extra time on
re-formatting my writing from the ground up. It was thus pretty obvious that I
would give a try to the built-in [[https://orgmode.org/manual/Publishing.html][org-publish]] package for Emacs as it is exactly
what I am looking for: automated and configurable exporting of Org projects to
HTML files, as plain as possible. There exist quite a few other projects which
turn a collection of Org files into a website, such as [[https://gohugo.io/][Hugo]] or [[https://github.com/bastibe/org-static-blog][org-static-blog]].
But I figured I would like to retain maximal control over the exporting process
and keep external dependencies as low as possible so I stuck to /org-publish/.

Using git versioning gives me the opportunity to track and manage changes over
time. Since we are dealing with a static website with exclusively public data,
[[https://github.io][github.io]] will handle the hosting for me. Whenever I want to work on a new item,
I can pull the remote github repository, create a local branch and start
editing. When the content is ready for publishing, the branch is merged into
main, pushed to the remote github repository and /voilà/!

* Project layout
:PROPERTIES:
:CUSTOM_ID: project-layout
:END:

I ended up with something like the following directory structure for this
project. The github repository containing all the up-to-date source files can be
found [[https://github.com/fuzztheplanet/fuzztheplanet.github.io][here]].

#+begin_src terminal
- ~/org/blog/
  - static/
    - css/
    - fonts/
    - img/
  - src/
    - index.org
    - about.org
    - posts/
      - hello.org
      - super-dupa-post.org
  - templates/
    - header.html
    - footer.html
    - post.org
  - Makefile
  - publish-website.el
  - README.org
#+end_src

*src/* contains the Org files that will be published to HTML. These files are
declaring as few exporting options as possible so that they can easily be used
in other contexts or projects. Global exporting options will be defined in
*publish-website.el* and page-specific options provided via *templates/* or, in
rare cases, directly in the files themselves. The *static/* directory hosts
assets such as stylesheets, fonts, images, etc. that will be exported "as is".

The logic behind publishing is implemented in *publish-website.el* which is
called by a *Makefile* for convenience. It defines all the directories, files
and exporting options that will be fed into /org-publish/. I could have written
my *publish-website.el* in literate programming style and use it as source for
this blog post, but that would have been a little bit too meta, even for me :)

Finally, *README.org* is just a symbolic link to *src/about.org*. Why? Because
we can!

* To the first page!
:PROPERTIES:
:CUSTOM_ID: first-page
:END:
*** Source files
:PROPERTIES:
:CUSTOM_ID: source-files
:END:

This is for example the beginning of [[https://github.com/fuzztheplanet/fuzztheplanet.github.io/blob/main/src/posts/hello-world-from-org.org][this post]]. It does not contain much beside
a title, a date, a template and a table of content. There is also a custom
=preview= block, but more on that a little bit later.

#+caption: posts/hello-world-from-org.org
#+begin_src org
,#+TITLE: Hello World from Org
,#+DATE: [2025-05-25 Sun]
,#+INCLUDE: ../../templates/post.org

,#+begin_preview
I describe /yet-another-simple-publishing-setup/ for a static website using
Emacs's [[https://orgmode.org/][Org mode]]. While there are plenty of resources on the topic available
already, I wanted to document my setup here for self-reference. Maybe someone
will take away an idea or two.
,#+end_preview

,#+begin_src sh
skywhi@dreamland:~/blog$ echo "Hello World Wild Web!" > posts/hello.org
skywhi@dreamland:~/blog$ make update && make publish
skywhi@dreamland:~/blog$ # make blogging great again!
,#+end_src

,{{{toc(Contents:,6)}}}

,* Rationale
:PROPERTIES:
:CUSTOM_ID: rationale
:END:

I figured the time had come to host some of my modest content online for
sharing, fun, persistence, easy access and all the other usual suspects. Going
into this adventure there were only a few requirements that I wanted my website
to meet: [...]
#+end_src

Appending a =CUSTOM_ID= property (=C-c C-x p=) to headings makes it possible to
link to them in the HTML. [[#source-files][This example link]] points to the present section.

The =toc= macro above is my own; it expands to a bold caption followed by a
=#+TOC= keyword so that every page declares its table of content the same way.
It is defined along with the other macros [[#publish-website][further down]].

*** Templates
:PROPERTIES:
:CUSTOM_ID: templates
:END:

When several Org files share the same rendering and exporting options, it can
make sense to regroup them in an Org template file and use the =#+SETUPFILE= or
=#+INCLUDE= directive in the relevant source files.

For example, the template under [[https://github.com/fuzztheplanet/fuzztheplanet.github.io/blob/main/templates/post.org][templates/post.org]] will extract the =date=
directive of the source file and add custom HTML to the post.

#+caption: templates/post.org
#+begin_src org
@@html:<span class="post-date">@@
/First published: {{{date(%d %b %Y)}}}/
@@html:</span>@@
#+end_src

*** CSS styling
:PROPERTIES:
:CUSTOM_ID: css
:END:

The two files that are used are [[https://github.com/fuzztheplanet/fuzztheplanet.github.io/blob/main/static/css/style.css][style.css]] and [[https://github.com/fuzztheplanet/fuzztheplanet.github.io/blob/main/static/css/htmlize.css][htmlize.css]]. The first hosts all
the base styles for the website while the second prettifies source code blocks
by redefining various =.org-*= CSS classes. Since I am aiming for a small and
flexible website I decided to write my own CSS manually (and I suck at it tbh).
People who don't want to enjoy the same +painful+ wonderful experience should
try to look for pre-existing stylesheets and nice exporting options.

*** Building and publishing
:PROPERTIES:
:CUSTOM_ID: publishing
:END:
***** publish-website.el
:PROPERTIES:
:CUSTOM_ID: publish-website
:END:

It was hyped for long enough, here is the [[https://github.com/fuzztheplanet/fuzztheplanet.github.io/blob/main/publish-website.el][publish-website.el]] file. This file
defines common settings and build instructions for the project. We feed them
into /org-publish/ which will take care of producing the corresponding website.

The file is pretty simple and self-explanatory. I mostly added the following
functions to generate a "preview" of each post, which will be visible in the
[[./index.org][list of all posts]], as well as include a formatted timestamp of when the post was
first added. A custom macro is used to format the timestamp. The content of the
"preview" is written in between the custom =#+begin_preview= and =#+end_preview=
tags.

#+caption: publish-website.el
#+begin_src emacs-lisp
;; Preview block
(defun skw-blog/get-preview (file)
  "Extract the content between #+begin_preview and #+end_preview blocks
   in 'file'. The block tags have to be on their own lines, preferably
   before and after paragraphs."
  (with-temp-buffer
    (message file)
    (insert-file-contents file)
    (goto-char (point-min))
    (let ((beg (+ 1 (re-search-forward "^#\\+begin_preview$")))
          (end (progn (re-search-forward "^#\\+end_preview$")
                      (match-beginning 0))))
      (replace-regexp-in-string "\n" " " (buffer-substring beg end)))))


;; Format list of blog post for the sitemap / index
(defun skw-blog/org-format-blog-post (entry style project)
  "Format 'entry' in org-publish 'project' sitemap to include a timestamp."
  (let ((entry-title (org-publish-find-title entry project)))
    (if (= (length entry-title) 0)
        (format "*%s*" entry)
      (format "{{{timestamp(%s)}}}: [[file:%s][%s]]"
              (format-time-string "%Y-%m-%d" (org-publish-find-date entry project))
              entry
              entry-title))))


;; Same but add the content between the "preview" tags
(defun skw-blog/org-format-blog-post-with-preview (entry style project)
  "Format 'entry' in org-publish 'project' sitemap to include a timestamp
   and preview ('begin/end_preview' tag)."
  (let ((entry-title (org-publish-find-title entry project))
        (preview (skw-blog/get-preview (concat (skw-blog/get-root-directory) "src/posts/" entry)))) ;; dirty
    (if (= (length entry-title) 0)
        (format "*%s*" entry)
      (format "{{{timestamp(%s)}}}: [[file:%s][%s]]\n
%s"
              (format-time-string "%Y-%m-%d" (org-publish-find-date entry project))
              entry
              entry-title
              preview))))


;; Exporting macros
(setq org-export-global-macros
      '(("timestamp" . "@@html:<span class=\"timestamp\">$1</span>@@")
        ("toc" . "*$1*\n#+TOC: headlines $2 local")))
#+end_src

The site header lives in *templates/header.html* and is injected as the HTML
preamble. Rather than serving the same markup everywhere, a small function marks
the navigation entry matching the page being exported with =aria-current= so
that the current section can be styled (and announced by screen readers).

The =<head>= of every page also advertises the RSS feed, which lets readers
subscribe from any page instead of having to find the feed by hand.

#+caption: publish-website.el
#+begin_src emacs-lisp
;; Feed autodiscovery, so readers can find the feed from any page
(setq skw-blog/rss-link
      (concat "<link rel=\"alternate\" type=\"application/rss+xml\" title=\""
              skw-blog/rss-feedname "\" href=\"/rss.xml\">\n"))


(defun skw-blog/nav-href-for (input-file)
  "Return the header nav href matching 'input-file', or nil when none does."
  (let ((f (or input-file "")))
    (cond ((string-match-p "/posts/" f)        "/posts/")
          ((string-match-p "/notes/" f)        "/notes/")
          ((string-match-p "links\\.org\\'" f) "/links.html")
          ((string-match-p "now\\.org\\'" f)   "/now.html")
          ((string-match-p "about\\.org\\'" f) "/about.html"))))


(defun skw-blog/html-preamble (info)
  "Return the site header, marking the nav entry for the page being exported."
  (let ((href (skw-blog/nav-href-for (plist-get info :input-file))))
    (if (null href)
        skw-blog/header
      (replace-regexp-in-string
       (concat "<a href=\"" (regexp-quote href) "\"")
       (concat "<a href=\"" href "\" aria-current=\"page\"")
       skw-blog/header t t))))
#+end_src

Wide tables used to drag the whole page sideways on narrow screens. An export
filter wraps every exported table in its own scrollable container, so only the
table scrolls. The =tabindex= makes that container reachable with the keyboard.

#+caption: publish-website.el
#+begin_src emacs-lisp
(defun skw-blog/wrap-table-in-scroll-container (table backend info)
  "Wrap an exported HTML 'table' in a horizontally scrollable container."
  (if (org-export-derived-backend-p backend 'html)
      (format "<div class=\"table-scroll\" tabindex=\"0\">\n%s</div>\n" table)
    table))

(add-to-list 'org-export-filter-table-functions
             #'skw-blog/wrap-table-in-scroll-container)
#+end_src

The following rules publish the Org files and generate 2 index files:
*posts/index.org* and *posts/index-no-preview.org*. The first one contains
previews of all posts and is published as the */posts/* page. The second one is
a bare list of the most recent posts which is only ever included into the
homepage, so its project uses a publishing function that writes nothing:
/org-publish/ always exports the sitemap it just generated, no matter what
=:exclude= says, and without this it would leave behind a stray page that
nothing links to.

Both index projects use it. The second one generates *posts/index.org*, which
does become a page -- but *website-src* walks *src/* recursively and already
exports it, along with the posts themselves. Leaving the publishing function
at its default would export every post a second time, to the exact same path.

#+caption: publish-website.el
#+begin_src emacs-lisp
(defun skw-blog/publish-nothing (_plist _filename _dir)
  "Publish nothing.  Used by projects that only exist to generate a sitemap."
  nil)


;; Build the homepage's "Latest posts" list, capped at the N most recent posts.
(defun skw-blog/format-latest-posts (title list)
  "Format the 'skw-blog/latest-posts-count' first entries of 'list' as a
sitemap titled 'title'."
  (let ((entries (seq-take (cdr list) skw-blog/latest-posts-count)))
    (concat "#+TITLE: " title "\n\n"
            (org-list-to-org (cons (car list) entries)))))
#+end_src

#+caption: publish-website.el
#+begin_src emacs-lisp
("website-src"
 :base-directory ,skw-blog/srcdir
 :base-extension "org"
 :exclude ,(regexp-opt '("rss.org" "index-no-preview.org"))

 :recursive t
 :publishing-directory ,skw-blog/outdir
 :publishing-function org-html-publish-to-html

 :auto-sitemap t
 :sitemap-title ,skw-blog/main-sitemap-title

 :html-preamble skw-blog/html-preamble
 :html-postamble ,skw-blog/footer
 :html-head ,(concat skw-blog/main-css skw-blog/favicon skw-blog/rss-link))

;; Bare list of the latest blog posts. Only generates an Org file that
;; the homepage includes; it is never published as a page of its own.
("website-posts-index"
 :base-directory ,(concat skw-blog/srcdir "posts")
 :base-extension "org"
 :exclude ,(regexp-opt '("rss.org" "index.org" "index-no-preview.org"))
 :publishing-directory ,(concat skw-blog/outdir "posts")
 :publishing-function skw-blog/publish-nothing

 :auto-sitemap t
 :sitemap-title "Latest posts"
 :sitemap-filename "index-no-preview.org"
 :sitemap-function skw-blog/format-latest-posts
 :sitemap-format-entry skw-blog/org-format-blog-post
 :sitemap-sort-files anti-chronologically)

;; Index of all blog posts with preview
("website-posts-index-preview"
 :base-directory ,(concat skw-blog/srcdir "posts")
 :base-extension "org"
 :exclude ,(regexp-opt '("rss.org" "index.org" "index-no-preview.org"))
 :publishing-directory ,(concat skw-blog/outdir "posts")
 :publishing-function skw-blog/publish-nothing

 :auto-sitemap t
 :sitemap-title "Posts"
 :sitemap-filename "index.org"
 :sitemap-format-entry skw-blog/org-format-blog-post-with-preview
 :sitemap-sort-files anti-chronologically)
#+end_src

The generated *src/posts/index-no-preview.org* is inserted into the homepage.
The cap lives in =skw-blog/latest-posts-count= rather than in the =#+INCLUDE=
itself, so the list can grow or its titles wrap without the homepage silently
truncating them.

#+caption: src/index.org
#+begin_src org
,#+INCLUDE: "./posts/index-no-preview.org" :lines "3-"
#+end_src

Order matters in the =:components= list: the two index projects have to run
/before/ *website-src*, since that is what exports the homepage including the
list they generate. The other way around, every freshly added post shows up on
the homepage one build late.

#+caption: publish-website.el
#+begin_src emacs-lisp
("website" :components
 ("website-posts-index" "website-posts-index-preview" "website-src"
  "website-rss" "website-files" "website-static"))
#+end_src

***** Makefile
:PROPERTIES:
:CUSTOM_ID: makefile
:END:

Let's use *make* to avoid building and managing the website by hand.

#+caption: Makefile
#+begin_src makefile
OUT_DIR='www'
PUBLISH_FILE='publish-website.el'
PUBLISH_FUNC='(org-publish "website")'
WS_CMD=python -m http.server 12345 --bind localhost --directory $(OUT_DIR)

all:
    rm -rf .cache www
    emacs -Q --batch --load $(PUBLISH_FILE) --eval $(PUBLISH_FUNC)
    rm -rf .cache

publish:
    git commit
    git push -u origin main

update:
    make all
    git add .
    git status

run:
    $(WS_CMD)

.PHONY: all mathjax publish update run
#+end_src

Whenever I want to work on a new item, like adding a new file or editing an
existing one, I switch to a new local branch in the git repository. I then
simply run =make= periodically while editing to visualize my changes. When I am
done, I merge the branch into my local main branch and run =make update= to
verify what will be committed and then =make publish= to push the changes on the
remote repository. Cherry on top, =make run= spawns a python web-server to view
the website locally at http://localhost:12345.

* A few more functionalities
:PROPERTIES:
:CUSTOM_ID: more
:END:
*** MathJax
:PROPERTIES:
:CUSTOM_ID: mathjax
:END:

[[https://www.mathjax.org/][MathJax]]' [[https://orgmode.org/manual/Math-formatting-in-HTML-export.html][Org mode support]] lets me export to HTML math formulas written in LaTeX.
Here are a couple of examples using inline code blocks and "proper" LaTeX
syntax.

#+begin_src org
If $a^2=b$ and \( b=2 \), then the solution must be either $$ a=+\sqrt{2} $$ or
\[ a=-\sqrt{2} \]

Look at this lonely equation I found:

\begin{equation}
y = x^2+1
\end{equation}
#+end_src

Which will be rendered like this:

If $a^2=b$ and \( b=2 \), then the solution must be either $$ a=+\sqrt{2} $$ or
\[ a=-\sqrt{2} \]

Look at this lonely equation I found:

\begin{equation}
y = x^2+1
\end{equation}

I install and update regularly /MathJax/ via the *Makefile* and then enable it
in *publish-website.el* via the =org-html-mathjax-options= variable. Since I
want to be able to view the website offline, I opted for a local install. Only
a shallow clone is needed, as the repository history is thrown away immediately
afterwards.

#+caption: Makefile
#+begin_src makefile
MATHJAX_DIR='static/js/mathjax'

mathjax:
    rm -rf $(MATHJAX_DIR)
    git clone --depth 1 https://github.com/mathjax/MathJax.git $(MATHJAX_DIR)
    rm -rf $(MATHJAX_DIR)/.git
#+end_src

#+caption: publish-website.el
#+begin_src emacs-lisp
(setq org-html-mathjax-options
      '((path "/static/js/mathjax/es5/tex-mml-chtml.js")
        (scale 1.0) (align "center") (font "mathjax-modern") (overflow "overflow")
        (tags "ams") (indent "0em") (multlinewidth "85%") (tagindent ".8em")
        (tagside "right")))
#+end_src

*** RSS feed
:PROPERTIES:
:CUSTOM_ID: resources
:END:

Generating a RSS to track when new posts are published is actually not that
complicated with [[https://github.com/emacsmirror/ox-rss][ox-rss]]. Here are a couple of helper functions to generate a
"sitemap" file named *rss.org* which will list all the entries under
*src/posts/* excluding the previously generated indexes. This file is then
converted to XML. The description field of each item is the content of the
=preview= tags used earlier.

#+caption: publish-website.el
#+begin_src emacs-lisp
;; RSS feed generation
(defun skw-blog/publish-to-rss (plist filename dir)
  "Publish 'plist' when 'filename' corresponds to RSS feed Org-file to 'dir'."
  (if (equal skw-blog/rss-filename (file-name-nondirectory filename))
      (org-rss-publish-to-rss plist filename dir)))

(defun skw-blog/format-rss-feed (title list)
  "Generate a sitemap of posts that will be exported as a RSS feed. 'title' is
title of the RSS feed and 'list' the files to be included."
  (concat "#+TITLE: " title "\n\n" (org-list-to-subtree list)))

(defun skw-blog/format-rss-feed-entry (entry style project)
  "Format 'entry' for the posts RSS feed in given 'project'."
  (let* ((title (org-publish-find-title entry project))
         (link (concat (file-name-sans-extension entry) ".html"))
         (pubdate (format-time-string (car org-time-stamp-formats)
                                      (org-publish-find-date entry project)))
         (preview (skw-blog/get-preview (concat (skw-blog/get-root-directory) "src/posts/" entry))))

    (format "%s
:properties:
:rss_permalink: %s
:pubdate: %s
:end:
%s" title link pubdate preview)))
#+end_src

These functions are then called inside a new publishing rule.

#+caption: publish-website.el
#+begin_src emacs-lisp
("website-rss"
 :base-directory ,(concat skw-blog/srcdir "posts")
 :base-extension "org"
 :recursive nil
 :exclude ,(regexp-opt '("rss.org" "index.org" "index-no-preview.org"))
 :publishing-directory ,skw-blog/outdir
 :publishing-function skw-blog/publish-to-rss

 :with-author t
 :author ,skw-blog/author
 :email ,skw-blog/email

 :description ,skw-blog/rss-description
 :rss-extension "xml"
 ;; The feed is published at the site root, not under /posts/, so the
 ;; self-referencing <atom:link> cannot be derived from :html-link-home.
 :rss-feed-url ,(concat skw-blog/upstream-url "/rss.xml")
 :rss-image-url ,(concat skw-blog/upstream-url "/static/img/profile.jpg")
 :html-link-home ,(concat skw-blog/upstream-url "/posts/")
 :html-link-use-abs-url t
 :html-link-org-files-as-html t

 :auto-sitemap t
 :sitemap-filename ,skw-blog/rss-filename
 :sitemap-title ,skw-blog/rss-feedname
 :sitemap-sort-files anti-chronologically
 :sitemap-function skw-blog/format-rss-feed
 :sitemap-format-entry skw-blog/format-rss-feed-entry)
#+end_src

* Resources
:PROPERTIES:
:CUSTOM_ID: resources
:END:

This publishing setup is quite rudimentary. I wrote this note mostly for self
reference in case I have to implement a similar project in the future. However,
I still hope it can help hesitating people to give a try to /org-publish/ and
see if it fits their needs. Maybe existing users could also get a tip or two out
of this. The full code is available on my [[https://github.com/fuzztheplanet/fuzztheplanet.github.io][github]].

I would encourage anyone fiddling with this to have the official documentation
right at hand: [[https://orgmode.org/][Org]], [[https://orgmode.org/manual/Publishing.html][Org-publish]] and [[https://orgmode.org/worg/][Worg]]. Here are websites that inspired me for
this adventure. I highly recommend that you check them out:

- [[https://www.taingram.org/blog/org-mode-blog.html][Building a Emacs Org-Mode Blog]] by [[https://www.taingram.org/][Thomas Ingram]] showcases a simple yet
  effective setup.
- [[https://ogbe.net/blog/blogging_with_org.html][Blogging using org-mode (and nothing else)]] by [[https://ogbe.net/][Dennis Ogbe]] is a really neat
  explanations and setup with Org-file pre-processing before publishing.
- [[https://ryuslash.org/literate-build.html][A literate programming example]] by [[https://ryuslash.org/][ryuslash]].


*Edit* [2026-01-27 Tue]: Updated directory structure and rephrased some
 sections.
