#+TITLE: Welcome to my little patch of internet!

Where I live on a diet of salted caramel, questionable code and self-inflicted
chaos - hunting bugs, taming ciphers, entertaining a love-hate relationship with
Emacs, surviving life, surviving Emacs and many other curiosities while casually
pretending I know what I’m doing in /#infosec/. Visitors be warned, this blog is
not a polished magazine whatsoever; it’s merely a patchwork of rants,
experiments and unfinished work, written in plain language.

The occasional [[./posts/][~/posts]] host punctual, one-of topics while [[./notes/][~/notes]] point toward
more lengthy content that /might/ get updated over time (fingers crossed).
Resources that were particularly interesting to me are kept under [[./links.org][~/links]].
Information about this website and contact details can be found in the [[./about.org][~/about]]
page. What is currently on my mind is on my [[./now.org][~/now]] page.

With this out of the way, I wish you happy reading!

* Latest posts

#+INCLUDE: "./posts/index-no-preview.org" :lines "3-7"

A list of all blog posts is available [[file:./posts/index.org][here]]. The elderly are welcome to use the
[[./rss.xml][RSS feed]].
