#+TITLE: Welcome to my little patch of internet!

This is where I spend my days hunting insects, sweet-talking ciphers, dancing
the carioca, pondering questionable life decisions and arguing with Emacs as if
we were in a long-term relationship neither of us can leave. In the midst of all
this chaos, I aim to remain a humble student of the zen of pwn - seeking
glimpses of enlightenment through suspicious-looking code, elusive CTF flags and
sticky salted caramel treats.

Visitors be warned, this blog is not a polished magazine whatsoever; it is
merely a patchwork of rants, experiments and unfinished work, written in plain
language. [[./posts/][posts]] hosts sporadic, one-off topics while the [[./notes/][notes]] section contains
longer pieces that /might/ get updated over time (no promises, but optimism is
free). Particularly shiny resources are hoarded under [[./links.org][links]]. Information about
this website and contact details can be found under [[./about.org][about]]. What Emacs allows me
to share of my life resides on my [[./now.org][now]] page.

With this out of the way, I wish you happy reading!

*Latest posts*

#+INCLUDE: "./posts/index-no-preview.org" :lines "3-7"

A list of all blog posts is available [[file:./posts/index.org][here]]. The elderly are encouraged to use
the [[./rss.xml][RSS feed]].
