#+TITLE: Welcome to my little patch of internet!

This is where, sustained almost exclusively by delicious salted caramel and
suspicious-looking code, I spend my days hunting insects, sweet-talking pretty
ciphers, dancing the carioca, pondering questionable life decisions and arguing
with Emacs as if we were in a long-term relationship neither of us can leave.
Visitors be warned, this blog is not a polished magazine whatsoever; it’s merely
a patchwork of rants, experiments and unfinished work, written in plain
language.

[[./posts/][~/Posts]] host sporadic, one-off topics that showed up uninvited and refused to
leave. The [[./notes/][~/Notes]] section contains longer pieces that /might/ get updated over
time (no promises, but optimism is free). Particularly shiny resources are
hoarded under [[./links.org][~/Links]] while information about this website and contact details
can be found under [[./about.org][~/About]]. What Emacs allows me to share of my life resides on
my [[./now.org][~/Now]] page.

With this out of the way, I wish you happy reading!

* Latest posts

#+INCLUDE: "./posts/index-no-preview.org" :lines "3-7"

A list of all blog posts is available [[file:./posts/index.org][here]]. The elderly are welcome to use the
[[./rss.xml][RSS feed]].
