#+TITLE: Now

This is my [[https://nownownow.com/about][now]] page (inspired by [[https://sive.rs][Derek Siver]]'s [[https://sive.rs/nowff][/now movement]] and [[https://breakpoint.purrfect.fr/][cym13]]'s [[https://breakpoint.purrfect.fr/soc.html][Stream
of Consciousness]]). Here you will find a brief overview of my current activities
and points of focus as well as some random, unsorted and unfiltered thoughts.


* [2025-06-06 Fri]

I am trying to push myself to *document* my on-going things and *publish* what
could potentially be relevant to others. This could be my [[https://github.com/fuzztheplanet/dotfiles][own dotfiles]], some
offsec / CTF knowledge, the things I use [[https://orgmode.org/][Org mode]] for, small utilities that I
wrote and a few more. I have a lot of ideas in that direction, let's see if I
find the time to make some progress over the summer.

There are a few *gardening* and *houseplants* projects happening at the moment.
I recently made 3 sealed terrariums with some good-looking calatheas, dracaenas
and fittonias. It would be really nice if they stay healthy and pretty. Some
paprika, cucumber and herbs made their way to my balcony. Hopefully they can
provide as much as some of my existing herbs, which consist mostly of mint,
lavender, rosemary, oregano and parsley. In the end, the best I can hope for is
that I kill them slower than my indoor plants.

I enjoy cooking and would like to start recording my favorite recipes in my own
*cookbook*.

I'm listening to a lot of [[https://www.youtube.com/channel/UCXOyTi7Hz5-c7YdjGPNiIPQ][Hubert-Félix Thiéfaine]] and [[https://www.youtube.com/watch?v=NLorCIJvF4w][cumbia]] lately.
