#+TITLE: Now

This is my [[https://nownownow.com/about][now]] page (inspired by [[https://sive.rs][Derek Siver]]'s [[https://sive.rs/nowff][/now movement]] and [[https://breakpoint.purrfect.fr/][cym13]]'s [[https://breakpoint.purrfect.fr/soc.html][Stream
of Consciousness]]). Here you will find a brief overview of my current activities
and points of focus as well as some random, unsorted and unfiltered ramblings.

* [2026-08-23 Sun]
:PROPERTIES:
:CUSTOM_ID: 2026-08-23
:END:

I am the proud owner of a 4-month-old Mini Aussie called /Yoga/. Which means my
days are now divided between Emacs, questionable amounts of coffee and being
outsmarted by a creature weighing 6.7 kg. He is extremely playful, energetic,
and convinced that my slippers should be hearded with special care. Yoga
definitely is the best looking puppy in town and he owns it.

As usual I'm late to the party but I've started dabbling with AI for some
trivial tasks such as performing security source code analysis or writing naive
Bash or Python tooling. The next step is to unleash it on my regular projects:
this blog, my tools and my knowledge base for example, to see how it can enhance
my existing workflow. Much like the puppy, I suspect it will require some
training, supervision and occasional damage control but the process will be
enjoyable and the results most likely more than satisfaying.

* [2025-12-04 Thu]
:PROPERTIES:
:CUSTOM_ID: 2025-12-04
:END:

The end of the year is approaching slowly but surely.

Last summer was quite busy with family visiting for a long time so I haven't
gotten the time to make the progress that I desired on my own personal topics. I
was however able to rework my [[file:posts/gtd-with-org.org]["Getting Things Done" setup]] which helps me
organize my tasks and plan my time better.

Spring and summer did yield a good harvest, considering it was the first time
that I planted vegetables and herbs. I will definitely continue next year.

Otherwise I am looking forward to celebrate the end of the year with my loved
ones and take some, hopefully well-deserved, time off from work.


* [2025-06-06 Fri]
:PROPERTIES:
:CUSTOM_ID: 2025-06-06
:END:

I am trying to push myself to *document* my on-going things and *publish* what
could potentially be relevant to others. This could be my [[https://github.com/fuzztheplanet/dotfiles][own dotfiles]], some
offsec / CTF knowledge, the things I use [[https://orgmode.org/][Org mode]] for, small utilities that I
wrote and a few more. I have a lot of ideas in that direction, let's see if I
find the time to make some progress over the summer.

There are a few *gardening* and *houseplants* projects happening at the moment.
I recently made 3 sealed terrariums with some good-looking calatheas, dracaenas
and fittonias. It would be really nice if they stay healthy and pretty. Some
paprika, cucumber and herbs made their way to my balcony. Hopefully they can
provide as much as some of my existing herbs, which consist mostly of mint,
lavender, rosemary, oregano and parsley. In the end, the best I can hope for is
that I kill them slower than my indoor plants.

I enjoy cooking and would like to start recording my favorite recipes in my own
*cookbook*.

I'm listening to a lot of [[https://www.youtube.com/channel/UCXOyTi7Hz5-c7YdjGPNiIPQ][Hubert-Félix Thiéfaine]] and [[https://www.youtube.com/watch?v=NLorCIJvF4w][cumbia]] lately.
